/* create a line that can be added to the table in the  action table of the page
 The 3 parameters are :
 - userAction : number which is the value of the button clicked by the userAction
 - aiAction : number value generated by the AI 
 - resultAction : the result of the action
  */



function createActionLine(userAction, aiAction,resultAction){

    var actionLine = document.createElement("tr");
    var userActionCell = document.createElement("td");
    var aiActionCell = document.createElement("td");
    var resultActionCell = document.createElement("td");

    userActionCell.innerHTML=getActionLabel(userAction);
    aiActionCell.innerHTML=getActionLabel(aiAction);
    resultActionCell.innerHTML=getResultActionLabel(resultAction);

    actionLine.appendChild(userActionCell);
    actionLine.appendChild(aiActionCell);
    actionLine.appendChild(resultActionCell);

    return actionLine;
}

function getActionLabel(numberAction){
    if(numberAction===1){
        return "<i class=\"fas fa-fist-raised\"></i> Physical attack";
    }else if(numberAction===2){
        return "<i class=\"fas fa-hat-wizard\"></i> Magical attack";
    }else if(numberAction===3){
        return "<i class=\"fas fa-shield-alt\"></i> Defense";
    }
}

function getResultActionLabel(resultAction){
    if(resultAction===1){
        return "<i class=\"fas fa-grin-beam\"></i> You hurt your opponent!";
    }else if(resultAction===-1){
        return "<i class=\"fas fa-frown-open\"></i> Your opponent hurt you!";
    }else if(resultAction===0){
        return "<i class=\"fas fa-meh-blank\"></i> Nothing happens.";
    }
}